.PHONY: deploy-dev infra-dev migration-dev start-dev stop-dev start-admin stop-admin start-eleve stop-eleve

_get_dev=$(shell grep '^$(1)=' $(SECRETS_FILE_DEV) | cut -d= -f2)

dev: infra-dev migration-dev cyber_note db-to-code-dev start-dev

# ── Infra ─────────────────────────────────────────────────────────────────────

infra-dev:
	@echo "--- 🐳 Démarrage des conteneurs Docker ---"
	cd $(DOCKER_DIR) && docker compose -f compose.yaml --env-file ../../$(SECRETS_FILE_DEV) up -d

	@echo "--- 🗑️ suppression de la bd db_rex ---"
	docker exec -i postgres-16.10-alpine-rex psql -U postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'db_rex';"
	docker exec -i postgres-16.10-alpine-rex psql -U postgres -c "DROP DATABASE IF EXISTS db_rex;"
	@echo "--- 🆕 création de la bd db_rex ---"
	docker exec -i postgres-16.10-alpine-rex psql -U postgres -c "CREATE DATABASE db_rex;"

	@echo "--- 🗑️ suppression de la bd MariaDB ---"
	docker exec -i mariadb-rex mariadb -u root -p$(call _get_dev,MARIADB_PASSWORD) \
		-e "DROP DATABASE IF EXISTS $(call _get_dev,MARIADB_DB);"
	@echo "--- 🆕 création de la bd MariaDB ---"
	docker exec -i mariadb-rex mariadb -u root -p$(call _get_dev,MARIADB_PASSWORD) \
		-e "CREATE DATABASE $(call _get_dev,MARIADB_DB);"

# ── Migration ──────────────────────────────────────────────────────────────────────

migration-dev:
	$(INFRA_DIR)/migrate-v0-to-v1.sh $(SECRETS_FILE_DEV)

# ── Import des notes ──────────────────────────────────────────────────────────────────────

cyber_note:
	@echo "--- 🐬 Import des notes CyberNotes dans MariaDB ---"
	docker exec -i mariadb-rex mariadb \
		-u $(call _get_dev,MARIADB_USER) \
		-p$(call _get_dev,MARIADB_PASSWORD) \
		--skip-ssl  \
		$(call _get_dev,MARIADB_DB) < $(INFRA_DIR)/bd_data/dump_cyber_notes.sql

# ── Code ──────────────────────────────────────────────────────────────────────

db-to-code-dev:
	@echo "--- 🆕 gen code sqlc ---"
	$(INFRA_DIR)/db-to-code.sh $(SECRETS_FILE_DEV)

# ── Conteneurs locaux ─────────────────────────────────────────────────────────

start-dev: start-admin start-eleve

stop-dev: stop-admin stop-eleve

start-admin:
	$(RUN_DIR)/build-admin.sh dev
	$(RUN_DIR)/start-admin-dev.sh

start-eleve:
	$(RUN_DIR)/build-eleve.sh dev
	$(RUN_DIR)/start-eleve-dev.sh

stop-admin:
	@echo "--- 🛑 Arrêt du container admin ---"
	docker rm -f $(ADMIN_CONTAINER) 2>/dev/null || true

stop-eleve:
	@echo "--- 🛑 Arrêt du container élève ---"
	docker rm -f $(ELEVE_CONTAINER) 2>/dev/null || true

	
