.PHONY: local deploy-local infra-local stop-infra migration-local cyber_note start-local stop-local build-local build-admin-local start-admin stop-admin build-eleve-local start-eleve stop-eleve db-to-code-local

_get_local=$(shell grep '^$(1)=' $(SECRETS_FILE_LOCAL) | cut -d= -f2)

local:  infra-local migration-local cyber_note build-local  start-local


#
# ── Infra ─────────────────────────────────────────────────────────────────────

infra-local:
	@echo "--- 🐳 Démarrage des conteneurs Docker ---"
	cd $(DOCKER_DIR) && docker compose -f compose.yaml --env-file ../../$(SECRETS_FILE_LOCAL) up -d

	@echo "--- 🗑️ suppression de la bd db_rex ---"
	docker exec -i postgres-16.10-alpine-rex psql -U postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'db_rex';"
	docker exec -i postgres-16.10-alpine-rex psql -U postgres -c "DROP DATABASE IF EXISTS db_rex;"
	@echo "--- 🆕 création de la bd db_rex ---"
	docker exec -i postgres-16.10-alpine-rex psql -U postgres -c "CREATE DATABASE db_rex;"

	@echo "--- 🗑️ suppression de la bd MariaDB ---"
	docker exec -i mariadb-rex mariadb -u root -p$(call _get_local,MARIADB_PASSWORD) \
		-e "DROP DATABASE IF EXISTS $(call _get_local,MARIADB_DB);"
	@echo "--- 🆕 création de la bd MariaDB ---"
	docker exec -i mariadb-rex mariadb -u root -p$(call _get_local,MARIADB_PASSWORD) \
		-e "CREATE DATABASE $(call _get_local,MARIADB_DB);"

stop-infra:
	@echo "--- 🛑 Arrêt des conteneurs Docker ---"
	cd $(DOCKER_DIR) && docker compose -f compose.yaml --env-file ../../$(SECRETS_FILE_LOCAL) down

# ── Migration ──────────────────────────────────────────────────────────────────────

migration-local:
	$(INFRA_DIR)/migrate-v0-to-v1.sh $(SECRETS_FILE_LOCAL)

# ── Import des notes ──────────────────────────────────────────────────────────────────────

cyber_note:
	@echo "--- 🐬 Import des notes CyberNotes dans MariaDB ---"
	docker exec -i mariadb-rex mariadb \
		-u $(call _get_local,MARIADB_USER) \
		-p$(call _get_local,MARIADB_PASSWORD) \
		--skip-ssl  \
		$(call _get_local,MARIADB_DB) < $(INFRA_DIR)/bd_data/dump_cyber_notes.sql


# ── Conteneurs locaux ─────────────────────────────────────────────────────────

start-local: start-admin start-eleve

start-admin: fetch-freetsa-cert-if-missing build-admin-local
	$(RUN_DIR)/start-admin-local.sh

start-eleve: build-eleve-local
	$(RUN_DIR)/start-eleve-local.sh

stop-local: stop-admin stop-eleve stop-infra

build-local : build-admin-local build-eleve-local

build-admin-local: db-to-code-local
	$(RUN_DIR)/build-admin.sh local

build-eleve-local: db-to-code-local
	$(RUN_DIR)/build-eleve.sh local

db-to-code-local:
	@echo "--- 🆕 gen code sqlc ---"
	$(INFRA_DIR)/db-to-code.sh $(SECRETS_FILE_LOCAL)

stop-admin:
	@echo "--- 🛑 Arrêt du container admin ---"
	docker rm -f $(ADMIN_CONTAINER) 2>/dev/null || true

stop-eleve:
	@echo "--- 🛑 Arrêt du container élève ---"
	docker rm -f $(ELEVE_CONTAINER) 2>/dev/null || true
