.PHONY: infra-prod push deploy-prod

# ── Infra ─────────────────────────────────────────────────────────────────────

infra-prod: push deploy-prod

push:
	$(RUN_DIR)/push.sh

deploy-prod:
	@echo "--- 🚀 Déploiement sur les VMs prod ---"
	cd $(ANSIBLE_DIR) && ansible-playbook -i inventory/prod site.yml --extra-vars "@vault-vars.yml" --ask-vault-pass
