.PHONY: deploy-dev infra-dev migration-dev start-dev stop-dev start-admin stop-admin start-eleve stop-eleve

dev: infra-dev migration-dev db-to-code-dev start-dev

# ── Infra ─────────────────────────────────────────────────────────────────────

infra-dev:
	@echo "--- 🐳 Démarrage des conteneurs Docker ---"
	cd $(DOCKER_DIR) && docker compose -f compose.yaml up -d

	@echo "--- 🗑️ suppression de la bd db_rex ---"
	docker exec -i postgres-16.10-alpine-rex psql -U postgres -c "DROP DATABASE IF EXISTS db_rex;"
	@echo "--- 🆕 création de la bd db_rex ---"
	docker exec -i postgres-16.10-alpine-rex psql -U postgres -c "CREATE DATABASE db_rex;"

# ── Migration ──────────────────────────────────────────────────────────────────────

migration-dev:
	$(INFRA_DIR)/migrate-v0-to-v1.sh $(SECRETS_FILE_DEV)

# ── Code ──────────────────────────────────────────────────────────────────────

db-to-code-dev:
	@echo "--- 🆕 gen code sqlc ---"
	$(INFRA_DIR)/db-to-code.sh $(SECRETS_FILE_DEV)

# ── Conteneurs locaux ─────────────────────────────────────────────────────────

start-dev: start-admin start-eleve

stop-dev: stop-admin stop-eleve

start-admin:
	$(RUN_DIR)/build-admin.sh dev
	$(RUN_DIR)/start-admin-dev.sh

start-eleve:
	$(RUN_DIR)/build-eleve.sh dev
	$(RUN_DIR)/start-eleve-dev.sh

stop-admin:
	@echo "--- 🛑 Arrêt du container admin ---"
	docker rm -f $(ADMIN_CONTAINER) 2>/dev/null || true

stop-eleve:
	@echo "--- 🛑 Arrêt du container élève ---"
	docker rm -f $(ELEVE_CONTAINER) 2>/dev/null || true

	
