


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE FUNCTION public.notify_new_feedback() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_promotion varchar(255);
  v_groupe    text;
BEGIN
  SELECT s.promotion INTO v_promotion
  FROM student s
  WHERE s.user_id = NEW.user_id;

  SELECT string_agg(g.name, ', ') INTO v_groupe
  FROM eleve_groupe eg
  JOIN groupe g ON g.id = eg.id_groupe
  WHERE eg.num_etudiant = NEW.user_id;

  PERFORM pg_notify(
    'new_feedback',
    json_build_object(
      'id',        NEW.id,
      'content',   NEW.content,
      'user_id',   NEW.user_id,
      'season_id', NEW.season_id,
      'promotion', v_promotion,
      'groupe',    v_groupe
    )::text
  );
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.eleve_groupe (
    num_etudiant integer NOT NULL,
    id_groupe integer NOT NULL
);



CREATE TABLE public.elo_history (
    id integer NOT NULL,
    user_id integer,
    season_id integer,
    final_elo integer NOT NULL,
    rank integer
);



CREATE SEQUENCE public.elo_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.elo_history_id_seq OWNED BY public.elo_history.id;



CREATE TABLE public.feedback (
    id integer NOT NULL,
    user_id integer,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    season_id integer,
    strongbox text,
    pseudo text,
    message_id text
);



CREATE TABLE public.feedback_classification (
    feedback_id integer NOT NULL,
    categorie character varying(64) NOT NULL,
    sous_categorie character varying(64) NOT NULL,
    sentiment character varying(16) NOT NULL,
    urgence integer NOT NULL,
    resume text NOT NULL,
    promotion text,
    groupe text,
    classified_at timestamp with time zone DEFAULT now() NOT NULL
);



CREATE SEQUENCE public.feedback_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.feedback_id_seq OWNED BY public.feedback.id;



CREATE TABLE public.groupe (
    id bigint NOT NULL,
    name character varying(255),
    promo_id bigint NOT NULL
);



CREATE TABLE public.postit (
    id integer NOT NULL,
    message_id text NOT NULL,
    texte text NOT NULL,
    auteur_id integer NOT NULL,
    cree_le timestamp with time zone DEFAULT now() NOT NULL
);



ALTER TABLE public.postit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.postit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.promotion (
    id bigint NOT NULL,
    name character varying(255)
);



CREATE TABLE public.refresh_tokens (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    token_version integer DEFAULT 1,
    session text DEFAULT ''::text NOT NULL
);



CREATE SEQUENCE public.refresh_tokens_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.refresh_tokens_id_seq OWNED BY public.refresh_tokens.id;



CREATE SEQUENCE public.refresh_tokens_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.refresh_tokens_user_id_seq OWNED BY public.refresh_tokens.user_id;



CREATE TABLE public.reponse (
    id integer NOT NULL,
    message_id text NOT NULL,
    contenu text NOT NULL,
    auteur text NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    lu boolean DEFAULT false NOT NULL
);



ALTER TABLE public.reponse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reponse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.season (
    id integer NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL
);



CREATE SEQUENCE public.season_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.season_id_seq OWNED BY public.season.id;



CREATE TABLE public.student (
    user_id integer NOT NULL,
    elo integer DEFAULT 1000 NOT NULL,
    last_elo_gain integer DEFAULT 0,
    promotion character varying(255) DEFAULT NULL::character varying
);



CREATE TABLE public."user" (
    id integer NOT NULL,
    version integer DEFAULT 1,
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    roles text[] DEFAULT ARRAY['ELEVE'::text] NOT NULL,
    blame boolean DEFAULT false
);



CREATE SEQUENCE public.user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.user_id_seq OWNED BY public."user".id;



ALTER TABLE ONLY public.elo_history ALTER COLUMN id SET DEFAULT nextval('public.elo_history_id_seq'::regclass);



ALTER TABLE ONLY public.feedback ALTER COLUMN id SET DEFAULT nextval('public.feedback_id_seq'::regclass);



ALTER TABLE ONLY public.refresh_tokens ALTER COLUMN id SET DEFAULT nextval('public.refresh_tokens_id_seq'::regclass);



ALTER TABLE ONLY public.refresh_tokens ALTER COLUMN user_id SET DEFAULT nextval('public.refresh_tokens_user_id_seq'::regclass);



ALTER TABLE ONLY public.season ALTER COLUMN id SET DEFAULT nextval('public.season_id_seq'::regclass);



ALTER TABLE ONLY public."user" ALTER COLUMN id SET DEFAULT nextval('public.user_id_seq'::regclass);



ALTER TABLE ONLY public.elo_history
    ADD CONSTRAINT elo_history_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.feedback_classification
    ADD CONSTRAINT feedback_classification_pkey PRIMARY KEY (feedback_id);



ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.groupe
    ADD CONSTRAINT groupe_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.eleve_groupe
    ADD CONSTRAINT pk_eleve_groupe PRIMARY KEY (num_etudiant, id_groupe);



ALTER TABLE ONLY public.postit
    ADD CONSTRAINT postit_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.promotion
    ADD CONSTRAINT promotion_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);



ALTER TABLE ONLY public.reponse
    ADD CONSTRAINT reponse_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_user_id_key UNIQUE (user_id);



ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT uq_feedback_message_id UNIQUE (message_id);



ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);



ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);



CREATE TRIGGER feedback_notify AFTER INSERT ON public.feedback FOR EACH ROW EXECUTE FUNCTION public.notify_new_feedback();



ALTER TABLE ONLY public.elo_history
    ADD CONSTRAINT elo_history_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.season(id);



ALTER TABLE ONLY public.elo_history
    ADD CONSTRAINT elo_history_student_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);



ALTER TABLE ONLY public.student
    ADD CONSTRAINT elo_student_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.season(id);



ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_student_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.feedback_classification
    ADD CONSTRAINT fk_classification_feedback FOREIGN KEY (feedback_id) REFERENCES public.feedback(id);



ALTER TABLE ONLY public.eleve_groupe
    ADD CONSTRAINT fk_eleve_groupe_eleve FOREIGN KEY (num_etudiant) REFERENCES public."user"(id);



ALTER TABLE ONLY public.eleve_groupe
    ADD CONSTRAINT fk_eleve_groupe_groupe FOREIGN KEY (id_groupe) REFERENCES public.groupe(id);



ALTER TABLE ONLY public.postit
    ADD CONSTRAINT fk_postit_feedback FOREIGN KEY (message_id) REFERENCES public.feedback(message_id) ON DELETE CASCADE;



ALTER TABLE ONLY public.postit
    ADD CONSTRAINT fk_postit_user FOREIGN KEY (auteur_id) REFERENCES public."user"(id);



ALTER TABLE ONLY public.reponse
    ADD CONSTRAINT fk_reponse_feedback FOREIGN KEY (message_id) REFERENCES public.feedback(message_id) ON DELETE CASCADE;



ALTER TABLE ONLY public.groupe
    ADD CONSTRAINT groupe_promo_id_fkey FOREIGN KEY (promo_id) REFERENCES public.promotion(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;




