


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;





CREATE FUNCTION public.notify_new_feedback() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM pg_notify(
    'new_feedback',
    json_build_object(
      'id',        NEW.id,
      'content',   NEW.content,
      'promotion', NEW.promotion,
      'groupe',    NEW.groupe
    )::text
  );
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.eleve_groupe (
    num_etudiant integer NOT NULL,
    id_groupe integer NOT NULL
);



CREATE TABLE public.eval_chip_ref (
    id text NOT NULL,
    dimension text NOT NULL,
    polarite text NOT NULL,
    libelle text NOT NULL,
    display_order smallint DEFAULT 0,
    actif boolean DEFAULT true
);



CREATE TABLE public.eval_chip_reponse (
    session_id uuid NOT NULL,
    chip_id text NOT NULL
);



CREATE TABLE public.eval_scores (
    session_id uuid NOT NULL,
    score_peda_global smallint,
    score_peda_clarte smallint,
    score_contenu_adequation smallint,
    charge_perception character varying(10),
    charge_heures_semaine text,
    score_difficulte smallint,
    score_supports smallint,
    score_ambiance smallint,
    nps smallint,
    CONSTRAINT chk_charge_heures CHECK ((charge_heures_semaine = ANY (ARRAY['H_MOINS_1'::text, 'H_1_3'::text, 'H_3_5'::text, 'H_PLUS_5'::text]))),
    CONSTRAINT chk_charge_perception CHECK (((charge_perception)::text = ANY ((ARRAY['LEGERE'::character varying, 'ADAPTEE'::character varying, 'LOURDE'::character varying])::text[]))),
    CONSTRAINT chk_nps CHECK (((nps >= 0) AND (nps <= 10))),
    CONSTRAINT chk_score_ambiance CHECK (((score_ambiance >= 1) AND (score_ambiance <= 5))),
    CONSTRAINT chk_score_contenu CHECK (((score_contenu_adequation >= 1) AND (score_contenu_adequation <= 5))),
    CONSTRAINT chk_score_difficulte CHECK (((score_difficulte >= 1) AND (score_difficulte <= 5))),
    CONSTRAINT chk_score_peda_clarte CHECK (((score_peda_clarte >= 1) AND (score_peda_clarte <= 5))),
    CONSTRAINT chk_score_peda_global CHECK (((score_peda_global >= 1) AND (score_peda_global <= 5))),
    CONSTRAINT chk_score_supports CHECK (((score_supports >= 1) AND (score_supports <= 5)))
);



CREATE TABLE public.eval_session (
    id uuid NOT NULL,
    pseudo text NOT NULL,
    matiere_id bigint NOT NULL,
    format_suivi text NOT NULL,
    tendance_semestre text NOT NULL,
    assiduite text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    submitted_at timestamp with time zone
);



CREATE TABLE public.eval_synthese_ia (
    id uuid NOT NULL,
    matiere_id bigint NOT NULL,
    semestre text NOT NULL,
    nb_repondants integer NOT NULL,
    donnees_snapshot text,
    synthese_texte text NOT NULL,
    statut text DEFAULT 'GENEREE'::text NOT NULL,
    generated_at timestamp with time zone DEFAULT now() NOT NULL,
    validated_by text,
    validated_at timestamp with time zone
);



CREATE TABLE public.eval_verbatim (
    id uuid NOT NULL,
    session_id uuid NOT NULL,
    dimension text NOT NULL,
    texte text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    strongbox text,
    CONSTRAINT chk_verbatim_dimension CHECK ((dimension = ANY (ARRAY['SUPPORTS'::text, 'AMBIANCE'::text, 'NPS'::text])))
);



CREATE TABLE public.feedback (
    id integer NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    strongbox text,
    pseudo text,
    message_id text,
    promotion text,
    groupe text
);



CREATE TABLE public.feedback_classification (
    feedback_id integer NOT NULL,
    categorie character varying(64) NOT NULL,
    sous_categorie character varying(64) NOT NULL,
    sentiment character varying(16) NOT NULL,
    urgence integer NOT NULL,
    resume text NOT NULL,
    promotion text,
    groupe text,
    classified_at timestamp with time zone DEFAULT now() NOT NULL
);



CREATE SEQUENCE public.feedback_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.feedback_id_seq OWNED BY public.feedback.id;



CREATE TABLE public.groupe (
    id bigint NOT NULL,
    name character varying(255),
    taille integer NOT NULL,
    promo_id bigint NOT NULL
);



CREATE TABLE public.matiere (
    id bigint NOT NULL,
    external_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    periode_id bigint,
    annee integer NOT NULL
);



ALTER TABLE public.matiere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matiere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.periode (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    promotion_id bigint NOT NULL,
    annee integer NOT NULL
);



ALTER TABLE public.periode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.periode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.postit (
    id integer NOT NULL,
    message_id text NOT NULL,
    message_modere text,
    reponse text NOT NULL,
    auteur_id integer NOT NULL,
    cree_le timestamp with time zone DEFAULT now() NOT NULL
);



ALTER TABLE public.postit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.postit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.promotion (
    id bigint NOT NULL,
    name character varying(255)
);



CREATE TABLE public.refresh_tokens (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    token_version integer DEFAULT 1,
    session text DEFAULT ''::text NOT NULL
);



CREATE SEQUENCE public.refresh_tokens_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.refresh_tokens_id_seq OWNED BY public.refresh_tokens.id;



CREATE SEQUENCE public.refresh_tokens_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.refresh_tokens_user_id_seq OWNED BY public.refresh_tokens.user_id;



CREATE TABLE public.reponse (
    id integer NOT NULL,
    message_id text NOT NULL,
    contenu text NOT NULL,
    auteur text NOT NULL,
    cree_le timestamp with time zone NOT NULL,
    lu boolean DEFAULT false NOT NULL
);



ALTER TABLE public.reponse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reponse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.student (
    user_id integer NOT NULL,
    promotion character varying(255) DEFAULT NULL::character varying
);



CREATE TABLE public."user" (
    id integer NOT NULL,
    version integer DEFAULT 1,
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    roles text[] DEFAULT ARRAY['ELEVE'::text] NOT NULL,
    blame boolean DEFAULT false,
    informed_at timestamp with time zone
);



CREATE SEQUENCE public.user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE public.user_id_seq OWNED BY public."user".id;



ALTER TABLE ONLY public.feedback ALTER COLUMN id SET DEFAULT nextval('public.feedback_id_seq'::regclass);



ALTER TABLE ONLY public.refresh_tokens ALTER COLUMN id SET DEFAULT nextval('public.refresh_tokens_id_seq'::regclass);



ALTER TABLE ONLY public.refresh_tokens ALTER COLUMN user_id SET DEFAULT nextval('public.refresh_tokens_user_id_seq'::regclass);



ALTER TABLE ONLY public."user" ALTER COLUMN id SET DEFAULT nextval('public.user_id_seq'::regclass);



ALTER TABLE ONLY public.eval_chip_ref
    ADD CONSTRAINT eval_chip_ref_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.eval_scores
    ADD CONSTRAINT eval_scores_pkey PRIMARY KEY (session_id);



ALTER TABLE ONLY public.eval_session
    ADD CONSTRAINT eval_session_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.eval_synthese_ia
    ADD CONSTRAINT eval_synthese_ia_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.eval_verbatim
    ADD CONSTRAINT eval_verbatim_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.feedback_classification
    ADD CONSTRAINT feedback_classification_pkey PRIMARY KEY (feedback_id);



ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.groupe
    ADD CONSTRAINT groupe_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.matiere
    ADD CONSTRAINT matiere_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.periode
    ADD CONSTRAINT periode_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.eleve_groupe
    ADD CONSTRAINT pk_eleve_groupe PRIMARY KEY (num_etudiant, id_groupe);



ALTER TABLE ONLY public.eval_chip_reponse
    ADD CONSTRAINT pk_eval_chip_reponse PRIMARY KEY (session_id, chip_id);



ALTER TABLE ONLY public.postit
    ADD CONSTRAINT postit_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.promotion
    ADD CONSTRAINT promotion_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);



ALTER TABLE ONLY public.reponse
    ADD CONSTRAINT reponse_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_user_id_key UNIQUE (user_id);



ALTER TABLE ONLY public.eval_session
    ADD CONSTRAINT uq_eval_session_pseudo_matiere UNIQUE (pseudo, matiere_id);



ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT uq_feedback_message_id UNIQUE (message_id);



ALTER TABLE ONLY public.matiere
    ADD CONSTRAINT uq_matiere_external_id_annee UNIQUE (external_id, annee);



ALTER TABLE ONLY public.periode
    ADD CONSTRAINT uq_periode_name_promotion_annee UNIQUE (name, promotion_id, annee);



ALTER TABLE ONLY public.eval_synthese_ia
    ADD CONSTRAINT uq_synthese_matiere_semestre_date UNIQUE (matiere_id, semestre, generated_at);



ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);



ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);



CREATE INDEX idx_chip_reponse_chip_id ON public.eval_chip_reponse USING btree (chip_id);



CREATE INDEX idx_eval_session_matiere ON public.eval_session USING btree (matiere_id);



CREATE INDEX idx_synthese_matiere_semestre ON public.eval_synthese_ia USING btree (matiere_id, semestre);



CREATE INDEX idx_verbatim_session ON public.eval_verbatim USING btree (session_id);



CREATE TRIGGER feedback_notify AFTER INSERT ON public.feedback FOR EACH ROW EXECUTE FUNCTION public.notify_new_feedback();



ALTER TABLE ONLY public.student
    ADD CONSTRAINT elo_student_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.eval_session
    ADD CONSTRAINT eval_session_matiere_id_fkey FOREIGN KEY (matiere_id) REFERENCES public.matiere(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.eval_synthese_ia
    ADD CONSTRAINT eval_synthese_ia_matiere_id_fkey FOREIGN KEY (matiere_id) REFERENCES public.matiere(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.eval_chip_reponse
    ADD CONSTRAINT fk_chip_reponse_ref FOREIGN KEY (chip_id) REFERENCES public.eval_chip_ref(id);



ALTER TABLE ONLY public.eval_chip_reponse
    ADD CONSTRAINT fk_chip_reponse_session FOREIGN KEY (session_id) REFERENCES public.eval_session(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.feedback_classification
    ADD CONSTRAINT fk_classification_feedback FOREIGN KEY (feedback_id) REFERENCES public.feedback(id);



ALTER TABLE ONLY public.eleve_groupe
    ADD CONSTRAINT fk_eleve_groupe_eleve FOREIGN KEY (num_etudiant) REFERENCES public."user"(id);



ALTER TABLE ONLY public.eleve_groupe
    ADD CONSTRAINT fk_eleve_groupe_groupe FOREIGN KEY (id_groupe) REFERENCES public.groupe(id);



ALTER TABLE ONLY public.postit
    ADD CONSTRAINT fk_postit_feedback FOREIGN KEY (message_id) REFERENCES public.feedback(message_id) ON DELETE CASCADE;



ALTER TABLE ONLY public.postit
    ADD CONSTRAINT fk_postit_user FOREIGN KEY (auteur_id) REFERENCES public."user"(id);



ALTER TABLE ONLY public.reponse
    ADD CONSTRAINT fk_reponse_feedback FOREIGN KEY (message_id) REFERENCES public.feedback(message_id) ON DELETE CASCADE;



ALTER TABLE ONLY public.eval_scores
    ADD CONSTRAINT fk_scores_session FOREIGN KEY (session_id) REFERENCES public.eval_session(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.eval_verbatim
    ADD CONSTRAINT fk_verbatim_session FOREIGN KEY (session_id) REFERENCES public.eval_session(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.groupe
    ADD CONSTRAINT groupe_promo_id_fkey FOREIGN KEY (promo_id) REFERENCES public.promotion(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.matiere
    ADD CONSTRAINT matiere_periode_id_fkey FOREIGN KEY (periode_id) REFERENCES public.periode(id) ON DELETE SET NULL;



ALTER TABLE ONLY public.periode
    ADD CONSTRAINT periode_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotion(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;




