database:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  name: ${POSTGRES_DB}

mariaDB:
  host:     ${MARIADB_HOST}
  port:     ${MARIADB_PORT}
  user:     ${MARIADB_USER}
  password: ${MARIADB_PASSWORD}
  database: ${MARIADB_DB}

server:
  host: localhost
  port: 3333

jwt:
  secret: ${JWT_SECRET_ADMIN}
  accessTokenExpiresIn: 15m
  refreshTokenExpiresIn: 2160h

ldap:
  #url: ldap://ldap.mines-ales.fr:389
  url: ldap://${LDAP_HOST}:389
  baseDN: dc=ema,dc=fr

ia:
  provider: rack # "ollama" ou "ragarenn" ou "rack"

ollama:
  baseURL: http://${OLLAMA_HOST}:11434
  model: mistral-nemo

ragarenn:
  baseURL: https://ragarenn.eskemm-numerique.fr/sso/ch@t
  apiKey: ${RAGARENN_API_KEY} 
  model: RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic # ilaas/gemma-4-31b  RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic

rack:
  baseURL: https://${IP_SERVEUR_IA_DEV}
  model: mistral-small:latest
  apiKey: ${RACK_API_KEY}
  caCertPath: /opt/rex-admin/certs/ca.crt