database:
  host: localhost
  port: 5432
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  name: db_rex  

mariaDB:
  host:     localhost
  port:     3306
  user:     ${MARIADB_USER}
  password: ${MARIADB_PASSWORD}
  database: cyber_notes_v2

server:
  host: localhost
  port: 3300

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiresIn: 15m
  refreshTokenExpiresIn: 168h

ldap:
#url: 	ldap://ldap.mines-ales.fr:389
  url: ldap://localhost:3890
  baseDN: dc=ema,dc=fr

age:
  publicKey: age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p
