database:
  host: ${HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  name: ${POSTGRES_DB}

mariaDB:
  host:     ${HOST}
  port:     ${MARIADB_PORT}
  user:     ${MARIADB_USER}
  password: ${MARIADB_PASSWORD}
  database: ${MARIADB_DB}

server:
  host: localhost
  port: 3300

jwt:
  secret: ${JWT_SECRET_ELEVE}
  accessTokenExpiresIn: 15m
  refreshTokenExpiresIn: 2160h

ldap:
#url: 	ldap://ldap.mines-ales.fr:389
  url: ldap://${HOST}:3890
  baseDN: dc=ema,dc=fr

age:
  publicKey: ${AGE_PUBLIC_KEY}
